### ISSUE TITLE
training on your own data

### ISSUE THREAD

**Issue by Malitem** [andy-yun/pytorch-0.4-yolov3#18]
So I want to train the network on my own data. I have images and and the .xml files for each image. If I understood correctly I have to create my.data file, but Im not quite sure what should i write in it. In coco.data there is written:
train  = coco_train.txt
valid  = coco_test.txt
names = data/names
backup = backup
gpus  = 0,1,2,3
What should I write in the train and valid section? Not sure what backup part does and Im not going to use any gpu. Any suggestions?

**Comment by Malitem** [comment]
in the names section I just created a names folder and wrote in the classes I want my network to know. There is not more than one in my case

**Comment by andy-yun** [comment]
1. train and valid includes the image files like
train.txt:
data/VOCdevkit/VOC2007/JPEGImages/000012.jpg
data/VOCdevkit/VOC2007/JPEGImages/000017.jpg
data/VOCdevkit/VOC2007/JPEGImages/000020.jpg

2. names includes class names as follows:
person
bicycle
car
motorbike
aeroplane
bus
train
truck
boat
traffic light

3. backup means the diectory where the weight files are saved when training

4. gpus means gnpu number (from zero to number of gpus - 1) you want to use.
If you don't want to use any gpus, you should modify some codes by your self.
This repository was created on the assumption of at least one gpu is used.

**Comment by Malitem** [comment]
What about my .xml files? Shouldn't I use them at all? How will the network learn an object without these files?

**Comment by Malitem** [comment]
I ran the voc_label.py file and all the xml files were remade into a txt files. But Im not quite sure how to use them

**Comment by andy-yun** [comment]
look the code in dataset.py, 68th line:
            labpath = imgpath.replace('images', 'labels').replace('JPEGImages', 'labels').replace('.jpg', '.txt').replace('.png','.txt')

text labels are obtained by the applying above command. 
So, you collect the images and save at the train.txt and valid.txt.

**Comment by nojorode** [comment]
I am also trying to train this model on my own data. I want to use the pretrained yolo-v3 weights, and continue the training on my own data. For the moment my data only consists of one class. Can I use the cfg/yolo_v3.cfg file for this? What modifications should I do, in order for the model to understand that there only is one class? Thanks in advance!

**Comment by doobidoob** [comment]
@nojorode Yes, you can use the cfg file.
You just change the "classes" in [yolo] layer and "filters" in [convolutional] layer (before the yolo layer) in cfg file.
Filter size is calculated to {num_Anchor Box * (5+ Num_class)}.
So in your case, filter size is 3*(5+1) = 18.
"5" means x, y, w, h, and confidence.

**Comment by nojorode** [comment]
Great, thank you very much!

**Comment by Malitem** [comment]
what for should i use voc_label.py then?

**Comment by andy-yun** [comment]
1. if you execute voc_label.py, then xml files are converted to txt files that represents the class id and bounding box (cx, cy, w, h)
2. separate and collect the text files to train.txt and valid.txt. 
3. modify the data file to assign the train.txt and valid.txt
4. train and test your model

**Comment by mrkieumy** [comment]
Hi, sorry for my naive question,
I looked at all your repo and test with your images is OK, but for training on my own dataset, I'm quite confused about some things: I have my own dataset: training have image/xml files. Testing too.
If I understand correctly that I did:
1. Make my names file: my.names (3 classes)
2. Copy yolov3.cfg --> yolov3-my.cfg and change number class (3) and filter (40).
3. Make my data file: my.data including 
     train  = trainlist.txt
     valid  = testlist.txt
     names = data/my.names
     backup = backup
     gpus  = 0,1,2,3
4. 2 files trainlist.txt and testlist.txt I put in this folder. But the dataset I put in other folder like: home/dataset/.../train, and test. Train images, test images and train annotations in the difference folder with each other. 
5. Replace the line 68 in dataset.py to get the label path from the train image path.
6. Run command to train: 
          python train.py -d cfg/my.data -c cfg/yolo_v3_my.cfg -w yolov3.weights -r
But the network didn't learn any, it showed like this (every row) for 476634 rows: 
     476634: Layer(106) nGT   0, nRC   0, nRC75   0, nPP   0, loss: box  0.000, conf  0.000, class  0.000, 
     total   0.000
That means every row is 0 all. And it takes me 2 days. I have 25.086 images. 

My question is: 
1. What wrong did I make in these steps? Is that the network look at the images name and automatically find the correct label having the same name?
2. What is the number 476634. I don't know how can I control the number of epochs because I don't understand the: max_batches = 500200, policy=steps, steps=400000,450000 in the *.cfg file ex. if I want to train 10 epochs on 25086 and save weight every epoch, what exactly number I fix?
I grateful with someone can help me.
Best regards.

**Comment by andy-yun** [comment]
1. In you log, nGT is 0. This means that your label file is not correctly loaded. You should check the label and image. For your convenience, you check the image and label in for loop of the train.py.
2. 47664 means the number of images entered the model. Actually, seen value. Max_batches used to calculate the efficient epoch number and policy and steps are used to control the learning rate. For the detail information, you shoud visit pjreddie/darknet sites.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SamuelKenne** [comment]
Thanks for the repo @andy-yun, I had to create an account for this reason. I'm trying to train on my own dataset to detect one class. I've followed the steps according to @Malitem and @mrkieumy questions however, I'm getting this weird error 

"~\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED"

I've shrunk the batch size to 1, I've also resized the images to be smaller (320x320), yet the problem still remains, I'm not sure what to do anymore, I've browsed the entire issues section of this repo and can't find a solution. Please, I'll deeply appreciate some help. Thank you.

Other info:
2 RTX 2080 Ti GPUs
290 training images
10 validation images

**Comment by SamuelKenne** [comment]
I seemed to have found a solution to this problem!

I felt the error was due to running out of memory, however, I just reinstalled the latest version of Pytorch and cuda and it works fine. Thanks
