### ISSUE TITLE
About the predicted result

### ISSUE THREAD

**Issue by lilyzhuang** [andy-yun/pytorch-0.4-yolov3#39]
Hi, Andy. I have two questions about the output.

1. I found that there is something wrong in the detected box. After using the function correct_yolo_boxes( ), the left, top of the box can be negative. 

e.g. -3.15759015083 26.1544475555 92.0868988037 106.778274536 

2. The conf_threshold used in testing is 0.5 while it is set to 0.25 in training. I think they should be the same.

Another question is about non-maximum suppression in training. I didn't find it in the training procedure. 
Do you use nms in the training procedure?

Many thanks.

**Comment by andy-yun** [comment]
1. The box might be detected at the out of image. But, I don't think that it is a bug. ^__^.
2. nPP results are shown over the value 0.25. You're right. But, sometimes, if you set a high value to threshold of nPP, you can see nPP = 0 very long time. Thus, I set the low value.

**Comment by andy-yun** [comment]
@LZZZZ29 you may got the error when the text box at the result is placed at out of image.
When the case, drawtext at utils.py shows exception error (ValueError).
I fixed that and uploaded new utils.py.

**Comment by lilyzhuang** [comment]
Sure. There is a problem in the location of the text box. Many thanks for your update. @andy-yun

**Comment by mrkieumy** [comment]
Hi @andy-yun and @LZZZZ29, sorry for asking an old question. I downloaded the newest utils.py but I don't know why the center coordinates still have minus value (-10,...). I do not understand it because I think center x and y calculate based on image size and it must be positive value right? 
Do you have any idea to solve it?
Thanks & best regards.
