### ISSUE TITLE
training text fles

### ISSUE THREAD

**Issue by dagap** [andy-yun/pytorch-0.4-yolov3#69]
Could you let us know what the coco_train.txt files and coco_test.txt files should look like? 
How do you specify the class labels and the bounding boxes? Are the bounding boxes normalized and the format is the centre coordinates and width, height?
It would be good if the README file can be updated with this information.

**Comment by andy-yun** [comment]
@dagap You can find the sample coco_train.txt and coco_test.txt files.
Thease files just include the image file list like as:
coco_train.txt:
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000009.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000025.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000030.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000034.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000036.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000049.jpg
/home/ysyun/Work/coco/images/train2014/COCO_train2014_000000000061.jpg
...

coco_test.txt:
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000164.jpg
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000192.jpg
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000283.jpg
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000397.jpg
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000589.jpg
/home/ysyun/Work/coco/images/val2014/COCO_val2014_000000000599.jpg
...

Because I am not the first developer of yolo series, I skipped the details.
